version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: crush-mysql
    restart: always
    environment:
      MYSQL_DATABASE: crush-db
      MYSQL_USER: crush-db-user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  fastapi:
    build:
      context: ../crush-fastapi
      dockerfile: Dockerfile
    container_name: crush-fastapi
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - fastapi-model-cache:/app/.cache/huggingface
    environment:
      - HF_HOME=/app/.cache/huggingface

volumes:
  fastapi-model-cache: