services:
  db:
    image: mysql:8.4
    container_name: crush-mysql
    restart: always
    environment:
      MYSQL_DATABASE: crush-db
      MYSQL_USER: crush-db-user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crush-spring
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      db:
        condition: service_healthy

  fastapi:
    build:
      context: ../Crush-FastAPI
      dockerfile: Dockerfile.local
    container_name: crush-fastapi
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MODEL_MODE=local
      - HF_HOME=/app/.cache/huggingface
    volumes:
      - fastapi-model-cache:/app/.cache/huggingface

volumes:
  fastapi-model-cache:
